name: CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'simple-agent/**'
      - '.github/workflows/ci-cd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'simple-agent/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Simple Agent
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './simple-agent/package-lock.json'
    
    - name: Install Dependencies
      working-directory: ./simple-agent
      run: npm ci
    
    - name: Check Code Format
      working-directory: ./simple-agent
      run: |
        npm run format:check || (echo "Code formatting check failed. Run 'npm run format' locally to fix." && exit 1)
    
    - name: Build
      working-directory: ./simple-agent
      run: npm run build
    
    - name: Deploy to Cloudflare Workers
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: ./simple-agent
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      run: npx wrangler@latest deploy 